require("./add_guest_by_invitation_test.coffee")
require("./edit_invitation_test.coffee")
require("./delete_invitation_test.coffee")
require("./show_invitations_list_test.coffee")
require("./confirm_invitation_delivery_test.coffee")
require("./confirm_invitation_assistance_test.coffee")
